services:
  - type: web
    name: bess-calculator
    env: node
    buildCommand: npm install
    startCommand: npm run production
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health
    autoDeploy: true 